name: CI/CD Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Continuous Integration (CI)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Testar o script
        run: python app.py

  deploy:
    name: Continuous Delivery (CD)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Simular Deploy
        run: echo "🚀 Fazendo o deploy da aplicação com sucesso!"